// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: serial.capnp

#pragma once

#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#if CAPNP_VERSION != 9001
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(daf710df78d5f02b);
CAPNP_DECLARE_SCHEMA(e36893f655ab4f94);
enum class Action_e36893f655ab4f94: uint16_t {
  GO,
  TALK,
  ATTACK,
  BUY,
  SELL,
};
CAPNP_DECLARE_ENUM(Action, e36893f655ab4f94);

}  // namespace schemas
}  // namespace capnp


struct Command {
  Command() = delete;

  class Reader;
  class Builder;
  class Pipeline;
  enum Which: uint16_t {
    EMPTY,
    WEAPON,
  };
  typedef ::capnp::schemas::Action_e36893f655ab4f94 Action;


  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(daf710df78d5f02b, 1, 1)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class Command::Reader {
public:
  typedef Command Reads;

  Reader() = default;
  inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

  inline Which which() const;
  inline  ::uint32_t getAmount() const;

  inline bool isEmpty() const;
  inline  ::capnp::Void getEmpty() const;

  inline bool isWeapon() const;
  inline bool hasWeapon() const;
  inline  ::capnp::Text::Reader getWeapon() const;

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class Command::Builder {
public:
  typedef Command Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  inline Builder(decltype(nullptr)) {}
  inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  inline operator Reader() const { return Reader(_builder.asReader()); }
  inline Reader asReader() const { return *this; }

  inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

  inline Which which();
  inline  ::uint32_t getAmount();
  inline void setAmount( ::uint32_t value);

  inline bool isEmpty();
  inline  ::capnp::Void getEmpty();
  inline void setEmpty( ::capnp::Void value = ::capnp::VOID);

  inline bool isWeapon();
  inline bool hasWeapon();
  inline  ::capnp::Text::Builder getWeapon();
  inline void setWeapon( ::capnp::Text::Reader value);
  inline  ::capnp::Text::Builder initWeapon(unsigned int size);
  inline void adoptWeapon(::capnp::Orphan< ::capnp::Text>&& value);
  inline ::capnp::Orphan< ::capnp::Text> disownWeapon();

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class Command::Pipeline {
public:
  typedef Command Pipelines;

  inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

inline  ::Command::Which Command::Reader::which() const {
  return _reader.getDataField<Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}
inline  ::Command::Which Command::Builder::which() {
  return _builder.getDataField<Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Command::Reader::getAmount() const {
  return _reader.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::uint32_t Command::Builder::getAmount() {
  return _builder.getDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Command::Builder::setAmount( ::uint32_t value) {
  _builder.setDataField< ::uint32_t>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Command::Reader::isEmpty() const {
  return which() == Command::EMPTY;
}
inline bool Command::Builder::isEmpty() {
  return which() == Command::EMPTY;
}
inline  ::capnp::Void Command::Reader::getEmpty() const {
  KJ_IREQUIRE((which() == Command::EMPTY),
              "Must check which() before get()ing a union member.");
  return _reader.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}

inline  ::capnp::Void Command::Builder::getEmpty() {
  KJ_IREQUIRE((which() == Command::EMPTY),
              "Must check which() before get()ing a union member.");
  return _builder.getDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS);
}
inline void Command::Builder::setEmpty( ::capnp::Void value) {
  _builder.setDataField<Command::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Command::EMPTY);
  _builder.setDataField< ::capnp::Void>(
      ::capnp::bounded<0>() * ::capnp::ELEMENTS, value);
}

inline bool Command::Reader::isWeapon() const {
  return which() == Command::WEAPON;
}
inline bool Command::Builder::isWeapon() {
  return which() == Command::WEAPON;
}
inline bool Command::Reader::hasWeapon() const {
  if (which() != Command::WEAPON) return false;
  return !_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline bool Command::Builder::hasWeapon() {
  if (which() != Command::WEAPON) return false;
  return !_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS).isNull();
}
inline  ::capnp::Text::Reader Command::Reader::getWeapon() const {
  KJ_IREQUIRE((which() == Command::WEAPON),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_reader.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline  ::capnp::Text::Builder Command::Builder::getWeapon() {
  KJ_IREQUIRE((which() == Command::WEAPON),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::get(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}
inline void Command::Builder::setWeapon( ::capnp::Text::Reader value) {
  _builder.setDataField<Command::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Command::WEAPON);
  ::capnp::_::PointerHelpers< ::capnp::Text>::set(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), value);
}
inline  ::capnp::Text::Builder Command::Builder::initWeapon(unsigned int size) {
  _builder.setDataField<Command::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Command::WEAPON);
  return ::capnp::_::PointerHelpers< ::capnp::Text>::init(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), size);
}
inline void Command::Builder::adoptWeapon(
    ::capnp::Orphan< ::capnp::Text>&& value) {
  _builder.setDataField<Command::Which>(
      ::capnp::bounded<2>() * ::capnp::ELEMENTS, Command::WEAPON);
  ::capnp::_::PointerHelpers< ::capnp::Text>::adopt(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS), kj::mv(value));
}
inline ::capnp::Orphan< ::capnp::Text> Command::Builder::disownWeapon() {
  KJ_IREQUIRE((which() == Command::WEAPON),
              "Must check which() before get()ing a union member.");
  return ::capnp::_::PointerHelpers< ::capnp::Text>::disown(_builder.getPointerField(
      ::capnp::bounded<0>() * ::capnp::POINTERS));
}


CAPNP_END_HEADER

